### ISSUE TITLE
build error.

### ISSUE THREAD

**Issue by NuLogicSystems** [DaveMDS/ede#1]
I'm getting this:
edje_cc: Error. parse error ../../../data/themes/default/default.edc:684. invalid state name: 'deafault'. "default" state must always be first

It looks like there may be some typos in the source code.
https://github.com/DaveMDS/ede/blob/master/data/themes/default/default.edc

**Comment by DaveMDS** [comment]
Thanks for reporting!

Now you can start writing some levels for ede :)

**Comment by NuLogicSystems** [comment]
Sounds good, I used to play defender at the skating rink when I was a teen. ;)
